[package]
name = "git-nest"
version = "0.0.1"
edition = "2021"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
description = "manage projects with (nested) git submodules"
readme = "README.md"
license = "MIT"
repository = "https://github.com/vhdirk/git-nest"

[lib]
name = "git_nest"
path = "src/lib.rs"

[[bin]]
name = "git-nest"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.5", features = ["derive"] }
colored = "3.0"
edit = "0.1"
git2 = { version = "0.21.0", features = ["cred"] }
serde = { version = "1.0.229", features = ["derive"] }
shell-words = "1.1.1"
tempfile = "3.14"
thiserror = "2.0.21"
toml = "1.1.2"
xdg = "3.0.0"

[profile.release]
lto = true
strip = true
