[book]
authors = ["Dirk Van Haerenborgh"]
language = "en"
src = "src"
title = "git-nest"
description = "Manage projects with (nested) git submodules"

[output.html]
git-repository-url = "https://github.com/vhdirk/git-nest"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = []

[rust]
edition = "2024"
